version: "3.8"
services:
  bot:
    build: .
    command: python bot.py
    volumes:
      - ./:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - DB_PATH=/app/ultrovpn.db
      - LOGO_PATH=/app/logo.png
      - PAY_WEBHOOK_SECRET=${PAY_WEBHOOK_SECRET}
    restart: unless-stopped

  webhook:
    build: .
    command: python webhook_aio.py
    volumes:
      - ./:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PAY_WEBHOOK_SECRET=${PAY_WEBHOOK_SECRET}
      - DB_PATH=/app/ultrovpn.db
    ports:
      - "5000:5000"
    restart: unless-stopped
